apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gor0a0c1r-go 
  janus-idp.io/tekton: gor0a0c1r-go
  backstage.io/kubernetes-id: gor0a0c1r-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gor0a0c1r-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml